// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sinsay.Domain;

#nullable disable

namespace Sinsay.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240516175836_mig")]
    partial class mig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sinsay.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastVisit")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isBloced")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@sinsay.ru",
                            PasswordHash = "ac9689e2272427085e35b9d3e3e8bed88cb3434828b43b86fc0596cad4c6e270",
                            RoleId = 1,
                            UserName = "Админ",
                            isBloced = false
                        },
                        new
                        {
                            Id = 2,
                            Email = "user@sinsay.ru",
                            PasswordHash = "831c237928e6212bedaa4451a514ace3174562f6761f6a157a2fe5082b36e2fb",
                            RoleId = 2,
                            UserName = "Иванов",
                            isBloced = false
                        });
                });

            modelBuilder.Entity("Sinsay.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Citys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Москва"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Санкт-Петербург"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Адыгея"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Альметьевск"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ангарск"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Арзамас"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Армавир"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Архангельск"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Астрахань"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Балаково"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Балашов"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Барабинск"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Барнаул"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Белгород"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Белебей"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Бердск"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Благовещенск"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Брянск"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Бугульма"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Великий Новгород"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Видное"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Владивосток"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Владикавказ"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Владимир"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Волгоград"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Волгодонск"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Волжский"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Воронеж"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Гатчина"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Грозный"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Десногорск"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Дзержинск"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Димитровград"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Домодедово"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Екатеринбург"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Жигулевск"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Иваново"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Ижевск"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Иркутск"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Йошкар-Ола"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Казань"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Калининград"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Калуга"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Кемерово"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Лениногорск"
                        });
                });

            modelBuilder.Entity("Sinsay.Models.Clothes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("Id");

                    b.ToTable("Clothes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 100,
                            Description = "сиреневый 40",
                            Name = "Платье-кардиган П 12 ",
                            Price = 1100m
                        },
                        new
                        {
                            Id = 2,
                            Count = 100,
                            Description = "черный 42",
                            Name = "Платье П 49 ",
                            Price = 990m
                        },
                        new
                        {
                            Id = 3,
                            Count = 100,
                            Description = "лиловый 42",
                            Name = "Платье П 50 ",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 4,
                            Count = 100,
                            Description = "бордо 46",
                            Name = "Платье П 59 ",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 5,
                            Count = 100,
                            Description = "черный + красный 46",
                            Name = "Платье П 27 ",
                            Price = 500m
                        },
                        new
                        {
                            Id = 6,
                            Count = 100,
                            Description = "красный 40",
                            Name = "Платье-кардиган П 12 ",
                            Price = 1100m
                        },
                        new
                        {
                            Id = 7,
                            Count = 100,
                            Description = "синий 40",
                            Name = "Платье-кардиган П 12 ",
                            Price = 1100m
                        },
                        new
                        {
                            Id = 8,
                            Count = 100,
                            Description = "серый+черный 42",
                            Name = "Платье П 32 ",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 9,
                            Count = 100,
                            Description = "розовый 42",
                            Name = "Пляжная накидка П 38 ",
                            Price = 700m
                        },
                        new
                        {
                            Id = 10,
                            Count = 100,
                            Description = "фуксия 46",
                            Name = "Платье П 02 ",
                            Price = 900m
                        },
                        new
                        {
                            Id = 11,
                            Count = 100,
                            Description = "хаки 42",
                            Name = "Платье П 58 ",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 12,
                            Count = 100,
                            Description = "черный 40",
                            Name = "Платье П 15 ",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 13,
                            Count = 100,
                            Description = "лимонный 48",
                            Name = "Платье П 28 ",
                            Price = 1300m
                        },
                        new
                        {
                            Id = 14,
                            Count = 100,
                            Description = "красный 42",
                            Name = "Платье-кардиган П 12 ",
                            Price = 1100m
                        },
                        new
                        {
                            Id = 15,
                            Count = 100,
                            Description = "сиреневый 42",
                            Name = "Платье-кардиган П 12 ",
                            Price = 1100m
                        },
                        new
                        {
                            Id = 16,
                            Count = 100,
                            Description = "черный 44",
                            Name = "Платье П 49 ",
                            Price = 990m
                        },
                        new
                        {
                            Id = 17,
                            Count = 100,
                            Description = "ментол 50",
                            Name = "Сарафан П 48 ",
                            Price = 800m
                        },
                        new
                        {
                            Id = 18,
                            Count = 100,
                            Description = "розовый 44",
                            Name = "Пляжная накидка П 38 ",
                            Price = 700m
                        },
                        new
                        {
                            Id = 19,
                            Count = 100,
                            Description = "черный 42",
                            Name = "Платье П 15 ",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 20,
                            Count = 100,
                            Description = "серый+черный 44",
                            Name = "Платье П 32 ",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 21,
                            Count = 100,
                            Description = "серый 44",
                            Name = "Платье П 46 ",
                            Price = 990m
                        },
                        new
                        {
                            Id = 22,
                            Count = 100,
                            Description = "фуксия 50",
                            Name = "Платье П 02 ",
                            Price = 900m
                        },
                        new
                        {
                            Id = 23,
                            Count = 100,
                            Description = "лимонный 50",
                            Name = "Платье П 28 ",
                            Price = 1300m
                        },
                        new
                        {
                            Id = 24,
                            Count = 100,
                            Description = "хвойный 52",
                            Name = "Платье П 59 ",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 25,
                            Count = 100,
                            Description = "серый+черный 54",
                            Name = "Платье П 32 ",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 26,
                            Count = 100,
                            Description = "хаки 46",
                            Name = "Платье П 58 ",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 27,
                            Count = 100,
                            Description = "серый 46",
                            Name = "Платье П 46 ",
                            Price = 990m
                        },
                        new
                        {
                            Id = 28,
                            Count = 100,
                            Description = "темно-синий 46",
                            Name = "Платье П 59 ",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 29,
                            Count = 100,
                            Description = "сиреневый 44",
                            Name = "Платье-кардиган П 12 ",
                            Price = 1100m
                        },
                        new
                        {
                            Id = 30,
                            Count = 100,
                            Description = "лиловый 46",
                            Name = "Платье П 50 ",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 31,
                            Count = 100,
                            Description = "черный 44",
                            Name = "Платье П 15 ",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 32,
                            Count = 100,
                            Description = "красный 50",
                            Name = "Платье П 02 ",
                            Price = 900m
                        },
                        new
                        {
                            Id = 33,
                            Count = 100,
                            Description = "серый+черный 56",
                            Name = "Платье П 32 ",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 34,
                            Count = 100,
                            Description = "лимонный 52",
                            Name = "Платье П 28 ",
                            Price = 1300m
                        },
                        new
                        {
                            Id = 35,
                            Count = 100,
                            Description = "красный 40",
                            Name = "Платье П 11 ",
                            Price = 1100m
                        },
                        new
                        {
                            Id = 36,
                            Count = 100,
                            Description = "красный 42",
                            Name = "Платье П 11 ",
                            Price = 1100m
                        },
                        new
                        {
                            Id = 37,
                            Count = 100,
                            Description = "красный 44",
                            Name = "Платье П 11 ",
                            Price = 1100m
                        },
                        new
                        {
                            Id = 38,
                            Count = 100,
                            Description = "красный 46",
                            Name = "Платье П 11 ",
                            Price = 1100m
                        },
                        new
                        {
                            Id = 39,
                            Count = 100,
                            Description = "индиго 4.1 M ",
                            Name = "Футболка мужская Ф 24 ",
                            Price = 1300m
                        },
                        new
                        {
                            Id = 40,
                            Count = 100,
                            Description = "сиреневый 9.1 XXL ",
                            Name = "Футболка мужская Ф 23 ",
                            Price = 1350m
                        },
                        new
                        {
                            Id = 41,
                            Count = 100,
                            Description = "голубой6 XXL ",
                            Name = "Футболка мужская Ф 23 ",
                            Price = 1350m
                        },
                        new
                        {
                            Id = 42,
                            Count = 100,
                            Description = "сиреневый7.1 XXL ",
                            Name = "Футболка мужская Ф 23 ",
                            Price = 1350m
                        },
                        new
                        {
                            Id = 43,
                            Count = 100,
                            Description = "белый ONE SIZE ",
                            Name = "Шапка бини В 03 ",
                            Price = 500m
                        },
                        new
                        {
                            Id = 44,
                            Count = 100,
                            Description = "бордо ONE SIZE ",
                            Name = "Шапка бини В 03 ",
                            Price = 500m
                        },
                        new
                        {
                            Id = 45,
                            Count = 100,
                            Description = "розовый ONE SIZE ",
                            Name = "Шапка бини В 03 ",
                            Price = 500m
                        },
                        new
                        {
                            Id = 46,
                            Count = 100,
                            Description = "розовый ONE SIZE ",
                            Name = "Шапка бини В 02 ",
                            Price = 500m
                        },
                        new
                        {
                            Id = 47,
                            Count = 100,
                            Description = "синий ONE SIZE ",
                            Name = "Шапка бини В 03 ",
                            Price = 500m
                        },
                        new
                        {
                            Id = 48,
                            Count = 100,
                            Description = "серый ONE SIZE ",
                            Name = "Шапка бини В 02 ",
                            Price = 500m
                        },
                        new
                        {
                            Id = 49,
                            Count = 100,
                            Description = "голубой 6 XXL ",
                            Name = "Блузка Ф 04 46",
                            Price = 500m
                        },
                        new
                        {
                            Id = 50,
                            Count = 100,
                            Description = "индиго 4.1 M ",
                            Name = "Блузка Ф 01 44",
                            Price = 502m
                        },
                        new
                        {
                            Id = 51,
                            Count = 100,
                            Description = "розовый 52-54",
                            Name = "Блузка Ф 01 46",
                            Price = 502m
                        },
                        new
                        {
                            Id = 52,
                            Count = 100,
                            Description = "горошек 44",
                            Name = "Блузка Ф 02 ",
                            Price = 550m
                        },
                        new
                        {
                            Id = 53,
                            Count = 100,
                            Description = "черный 58",
                            Name = "Блузка Ф 08 ",
                            Price = 650m
                        },
                        new
                        {
                            Id = 54,
                            Count = 100,
                            Description = "лиловый 44",
                            Name = "Блузка Ф 13 ",
                            Price = 750m
                        },
                        new
                        {
                            Id = 55,
                            Count = 100,
                            Description = "лиловый 46",
                            Name = "Блузка Ф 13 ",
                            Price = 750m
                        },
                        new
                        {
                            Id = 56,
                            Count = 100,
                            Description = "лиловый 50",
                            Name = "Блузка Ф 13 ",
                            Price = 750m
                        },
                        new
                        {
                            Id = 57,
                            Count = 100,
                            Description = "лиловый 56",
                            Name = "Блузка Ф 13 ",
                            Price = 750m
                        },
                        new
                        {
                            Id = 58,
                            Count = 100,
                            Description = "светло-зеленый 50",
                            Name = "Блузка Ф 13 ",
                            Price = 750m
                        },
                        new
                        {
                            Id = 59,
                            Count = 100,
                            Description = "светло-зеленый 54",
                            Name = "Блузка Ф 13 ",
                            Price = 750m
                        },
                        new
                        {
                            Id = 60,
                            Count = 100,
                            Description = "светло-зеленый 58",
                            Name = "Блузка Ф 13 ",
                            Price = 750m
                        },
                        new
                        {
                            Id = 61,
                            Count = 100,
                            Description = "розовый 40-42",
                            Name = "Футболка Ф 18 ",
                            Price = 516m
                        },
                        new
                        {
                            Id = 62,
                            Count = 100,
                            Description = "розовый 44-46",
                            Name = "Футболка Ф 18 ",
                            Price = 516m
                        },
                        new
                        {
                            Id = 63,
                            Count = 100,
                            Description = "розовый 52-54",
                            Name = "Футболка Ф 18 ",
                            Price = 516m
                        },
                        new
                        {
                            Id = 64,
                            Count = 100,
                            Description = "розовый 44-46",
                            Name = "Футболка Ф 19 ",
                            Price = 502m
                        },
                        new
                        {
                            Id = 65,
                            Count = 100,
                            Description = "розовый 48-50",
                            Name = "Футболка Ф 19 ",
                            Price = 502m
                        },
                        new
                        {
                            Id = 66,
                            Count = 100,
                            Description = "розовый 52-54",
                            Name = "Футболка Ф 19 ",
                            Price = 502m
                        },
                        new
                        {
                            Id = 67,
                            Count = 100,
                            Description = "индиго4.1 M ",
                            Name = "Футболка мужская Ф 24 ",
                            Price = 1300m
                        },
                        new
                        {
                            Id = 68,
                            Count = 100,
                            Description = "сиреневый7.1 XXL ",
                            Name = "Футболка мужская Ф 23 ",
                            Price = 1350m
                        },
                        new
                        {
                            Id = 69,
                            Count = 100,
                            Description = "сиреневый9.1 XXL ",
                            Name = "Футболка мужская Ф 23 ",
                            Price = 1350m
                        },
                        new
                        {
                            Id = 70,
                            Count = 100,
                            Description = "голубой6 XXL ",
                            Name = "Футболка мужская Ф 23 ",
                            Price = 1350m
                        },
                        new
                        {
                            Id = 71,
                            Count = 100,
                            Description = "розовый 42",
                            Name = "Толстовка Ф 14 ",
                            Price = 1033m
                        },
                        new
                        {
                            Id = 72,
                            Count = 100,
                            Description = "хаки 42",
                            Name = "Толстовка Ф 14 ",
                            Price = 1033m
                        },
                        new
                        {
                            Id = 73,
                            Count = 100,
                            Description = "ментол 62",
                            Name = "Худи Ф 20 ",
                            Price = 900m
                        },
                        new
                        {
                            Id = 74,
                            Count = 100,
                            Description = "хаки 44",
                            Name = "Толстовка Ф 14 ",
                            Price = 1033m
                        },
                        new
                        {
                            Id = 75,
                            Count = 100,
                            Description = "ментол 64",
                            Name = "Худи Ф 20 ",
                            Price = 900m
                        },
                        new
                        {
                            Id = 76,
                            Count = 100,
                            Description = "розовый 44",
                            Name = "Толстовка Ф 14 ",
                            Price = 1033m
                        },
                        new
                        {
                            Id = 77,
                            Count = 100,
                            Description = "ментол 66",
                            Name = "Худи Ф 20 ",
                            Price = 900m
                        },
                        new
                        {
                            Id = 78,
                            Count = 100,
                            Description = "хаки 46",
                            Name = "Толстовка Ф 14 ",
                            Price = 1033m
                        },
                        new
                        {
                            Id = 79,
                            Count = 100,
                            Description = "хаки 48",
                            Name = "Толстовка Ф 14 ",
                            Price = 1033m
                        },
                        new
                        {
                            Id = 80,
                            Count = 100,
                            Description = "розовый 48",
                            Name = "Толстовка Ф 14 ",
                            Price = 1033m
                        },
                        new
                        {
                            Id = 81,
                            Count = 100,
                            Description = "розовый 50",
                            Name = "Толстовка Ф 14 ",
                            Price = 1033m
                        },
                        new
                        {
                            Id = 82,
                            Count = 100,
                            Description = "розовый 52",
                            Name = "Толстовка Ф 14 ",
                            Price = 1033m
                        },
                        new
                        {
                            Id = 83,
                            Count = 100,
                            Description = "хаки 52",
                            Name = "Толстовка Ф 14 ",
                            Price = 1033m
                        },
                        new
                        {
                            Id = 84,
                            Count = 100,
                            Description = "персиковый 42",
                            Name = "Костюм К 25 ",
                            Price = 610m
                        },
                        new
                        {
                            Id = 85,
                            Count = 100,
                            Description = "синий 42",
                            Name = "Костюм К 17 ",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 86,
                            Count = 100,
                            Description = "персиковый 46",
                            Name = "Костюм К 25 ",
                            Price = 610m
                        },
                        new
                        {
                            Id = 87,
                            Count = 100,
                            Description = "синий 46",
                            Name = "Костюм К 17 ",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 88,
                            Count = 100,
                            Description = "синий 48",
                            Name = "Костюм К 17 ",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 89,
                            Count = 100,
                            Description = "персиковый 48",
                            Name = "Костюм К 25 ",
                            Price = 610m
                        },
                        new
                        {
                            Id = 90,
                            Count = 100,
                            Description = "синий 50",
                            Name = "Костюм К 17 ",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 91,
                            Count = 100,
                            Description = "персиковый 50",
                            Name = "Костюм К 25 ",
                            Price = 610m
                        },
                        new
                        {
                            Id = 92,
                            Count = 100,
                            Description = "синий 52",
                            Name = "Костюм К 17 ",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 93,
                            Count = 100,
                            Description = "ментол 52",
                            Name = "Костюм К 07 ",
                            Price = 1300m
                        },
                        new
                        {
                            Id = 94,
                            Count = 100,
                            Description = "персиковый 52",
                            Name = "Костюм К 25 ",
                            Price = 610m
                        },
                        new
                        {
                            Id = 95,
                            Count = 100,
                            Description = "розовый 42",
                            Name = "Костюм К 07 ",
                            Price = 1300m
                        },
                        new
                        {
                            Id = 96,
                            Count = 100,
                            Description = "розовый 46",
                            Name = "Костюм К 07 ",
                            Price = 1300m
                        },
                        new
                        {
                            Id = 97,
                            Count = 100,
                            Description = "розовый 50",
                            Name = "Костюм К 07 ",
                            Price = 1300m
                        },
                        new
                        {
                            Id = 98,
                            Count = 100,
                            Description = "розовый 52",
                            Name = "Костюм К 07 ",
                            Price = 1300m
                        },
                        new
                        {
                            Id = 99,
                            Count = 100,
                            Description = "розовый 42",
                            Name = "Костюм К 12 ",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 100,
                            Count = 100,
                            Description = "красный 42",
                            Name = "Костюм К 17 ",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 101,
                            Count = 100,
                            Description = "красный 46",
                            Name = "Костюм К 17 ",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 102,
                            Count = 100,
                            Description = "василек 42",
                            Name = "Костюм К 17 ",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 103,
                            Count = 100,
                            Description = "василек 46",
                            Name = "Костюм К 17 ",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 104,
                            Count = 100,
                            Description = "василек 50",
                            Name = "Костюм К 17 ",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 105,
                            Count = 100,
                            Description = "василек 52",
                            Name = "Костюм К 17 ",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 106,
                            Count = 100,
                            Description = "малиновый 42",
                            Name = "Брюки Ш 01 ",
                            Price = 700m
                        },
                        new
                        {
                            Id = 107,
                            Count = 100,
                            Description = "сиреневый 42",
                            Name = "Брюки Ш 01 ",
                            Price = 700m
                        },
                        new
                        {
                            Id = 108,
                            Count = 100,
                            Description = "сиреневый 44",
                            Name = "Брюки Ш 01 ",
                            Price = 700m
                        },
                        new
                        {
                            Id = 109,
                            Count = 100,
                            Description = "василек 44",
                            Name = "Брюки Ш 01 ",
                            Price = 700m
                        },
                        new
                        {
                            Id = 110,
                            Count = 100,
                            Description = "малиновый 46",
                            Name = "Брюки Ш 01 ",
                            Price = 700m
                        },
                        new
                        {
                            Id = 111,
                            Count = 100,
                            Description = "василек 46",
                            Name = "Брюки Ш 01 ",
                            Price = 700m
                        },
                        new
                        {
                            Id = 112,
                            Count = 100,
                            Description = "красная замша 46",
                            Name = "Брюки Ш 01 ",
                            Price = 800m
                        },
                        new
                        {
                            Id = 113,
                            Count = 100,
                            Description = "малиновый 48",
                            Name = "Брюки Ш 01 ",
                            Price = 700m
                        },
                        new
                        {
                            Id = 114,
                            Count = 100,
                            Description = "василек 48",
                            Name = "Брюки Ш 01 ",
                            Price = 700m
                        },
                        new
                        {
                            Id = 115,
                            Count = 100,
                            Description = "малиновый 52",
                            Name = "Брюки Ш 01 ",
                            Price = 700m
                        },
                        new
                        {
                            Id = 116,
                            Count = 100,
                            Description = "красный 42",
                            Name = "Брюки Ш 01 ",
                            Price = 700m
                        },
                        new
                        {
                            Id = 117,
                            Count = 100,
                            Description = "красный 44",
                            Name = "Брюки Ш 01 ",
                            Price = 700m
                        },
                        new
                        {
                            Id = 118,
                            Count = 100,
                            Description = "красный 46",
                            Name = "Брюки Ш 01 ",
                            Price = 700m
                        },
                        new
                        {
                            Id = 119,
                            Count = 100,
                            Description = "красный 50",
                            Name = "Брюки Ш 01 ",
                            Price = 700m
                        },
                        new
                        {
                            Id = 120,
                            Count = 100,
                            Description = "оранжевый 116см",
                            Name = "Детская футболка ДФ 01 ",
                            Price = 215m
                        },
                        new
                        {
                            Id = 121,
                            Count = 100,
                            Description = "фиолетовый 116см",
                            Name = "Детская футболка ДФ 01 ",
                            Price = 215m
                        },
                        new
                        {
                            Id = 122,
                            Count = 100,
                            Description = "оранжевый 122см",
                            Name = "Детская футболка ДФ 01 ",
                            Price = 215m
                        },
                        new
                        {
                            Id = 123,
                            Count = 100,
                            Description = "фиолетовый 122см",
                            Name = "Детская футболка ДФ 01 ",
                            Price = 215m
                        },
                        new
                        {
                            Id = 124,
                            Count = 100,
                            Description = "оранжевый 128см",
                            Name = "Детская футболка ДФ 01 ",
                            Price = 215m
                        },
                        new
                        {
                            Id = 125,
                            Count = 100,
                            Description = "фиолетовый 128см",
                            Name = "Детская футболка ДФ 01 ",
                            Price = 215m
                        },
                        new
                        {
                            Id = 126,
                            Count = 100,
                            Description = "фиолетовый 134см",
                            Name = "Детская футболка ДФ 01 ",
                            Price = 215m
                        },
                        new
                        {
                            Id = 127,
                            Count = 100,
                            Description = "оранжевый 134см",
                            Name = "Детская футболка ДФ 01 ",
                            Price = 215m
                        },
                        new
                        {
                            Id = 128,
                            Count = 100,
                            Description = "оранжевый 140см",
                            Name = "Детская футболка ДФ 01 ",
                            Price = 215m
                        },
                        new
                        {
                            Id = 129,
                            Count = 100,
                            Description = "фиолетовый 140см",
                            Name = "Детская футболка ДФ 01 ",
                            Price = 215m
                        });
                });

            modelBuilder.Entity("Sinsay.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<int>("PickupPointId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("PickupPointId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Sinsay.Models.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Принят в обработку"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Подтверждён"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Доставляется в ПВЗ"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Готов к выдаче"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Отменён"
                        });
                });

            modelBuilder.Entity("Sinsay.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Оплата картой при получении"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Оплата наличными при получении"
                        });
                });

            modelBuilder.Entity("Sinsay.Models.PickupPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PickupPoints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Московская область, п. Вешки, 1-й километр шоссе, 3с1",
                            CityId = 1,
                            Name = "ТЦ Весна"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Автозаводская улица, 18",
                            CityId = 1,
                            Name = "ТЦ Ривьера"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Ходынский б-р, 4",
                            CityId = 1,
                            Name = "ТЦ Авиапарк"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Московская область, г. Котельники, 1-й Покровский проезд, 5",
                            CityId = 1,
                            Name = "ТЦ МЕГА Белая Дача"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Московская область, п. Совхоз им. Ленина, 24-й километр МКАД, 1",
                            CityId = 1,
                            Name = "ТЦ Вегас"
                        },
                        new
                        {
                            Id = 6,
                            Address = "п. Московский, 23-ий км. Киевское шоссе, 1",
                            CityId = 1,
                            Name = "ТЦ Саларис"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Дмитрия Донского б-р, 1",
                            CityId = 1,
                            Name = "ТЦ Северное Сияние"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Кировоградская улица, 13А",
                            CityId = 1,
                            Name = "ТЦ Колумбус"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Аминьевско шоссе, 6",
                            CityId = 1,
                            Name = "ТЦ Квартал"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Мира пр-кт, 211к2",
                            CityId = 1,
                            Name = "ТЦ Европолис"
                        },
                        new
                        {
                            Id = 11,
                            Address = "7-я Кожуховская улица, 9",
                            CityId = 1,
                            Name = "ТЦ Мозаика"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Сущёвский Вал улица, 5 с 1А",
                            CityId = 1,
                            Name = "ТЦ Савеловский"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Рязанский пр-кт, 2К2",
                            CityId = 1,
                            Name = "ТЦ Город на Рязанке"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Каховка улица, 29А",
                            CityId = 1,
                            Name = "ТЦ Прайм Плаза"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Дмитровское шоссе, 163А",
                            CityId = 1,
                            Name = "ТЦ Рио"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Энтузиастов шоссе, 12к2",
                            CityId = 1,
                            Name = "ТЦ Город Лефортово"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Маршала Бирюзова улица, 32",
                            CityId = 1,
                            Name = "ТЦ 5 Авеню"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Сиреневый б-р, 31",
                            CityId = 1,
                            Name = "ТЦ София"
                        },
                        new
                        {
                            Id = 19,
                            Address = "Авиаторов улица, 3А",
                            CityId = 1,
                            Name = "ТЦ Небо"
                        },
                        new
                        {
                            Id = 20,
                            Address = "Новоухтомское шоссе, 2А стр.2",
                            CityId = 1,
                            Name = "ТЦ Город Косино» "
                        },
                        new
                        {
                            Id = 21,
                            Address = "г. Солнечногорск, 2-й мкр., С20",
                            CityId = 1,
                            Name = "ТЦ Зеленопарк"
                        },
                        new
                        {
                            Id = 22,
                            Address = "Ленинский проспект, 123В",
                            CityId = 1,
                            Name = "ТЦ Галеон"
                        },
                        new
                        {
                            Id = 23,
                            Address = "Коммунистическая ул., 1",
                            CityId = 1,
                            Name = "ТЦ XL"
                        },
                        new
                        {
                            Id = 24,
                            Address = "Ореховый бул., 22а",
                            CityId = 1,
                            Name = "ТЦ Облака"
                        },
                        new
                        {
                            Id = 25,
                            Address = "Ленинградская область, г. Кудрово, 12-й км. Мурманское шоссе, 1",
                            CityId = 2,
                            Name = "ТЦ МЕГА Дыбенко"
                        },
                        new
                        {
                            Id = 26,
                            Address = "Лиговский пр-кт, 30а",
                            CityId = 2,
                            Name = "ТЦ Галерея"
                        },
                        new
                        {
                            Id = 27,
                            Address = "Петергофское шоссе, 51",
                            CityId = 2,
                            Name = "ТЦ Жемчужина Плаза"
                        },
                        new
                        {
                            Id = 28,
                            Address = "Комендантская площадь, 1",
                            CityId = 2,
                            Name = "ТЦ Атмосфера"
                        },
                        new
                        {
                            Id = 29,
                            Address = "Балканская площадь, 5Ю",
                            CityId = 2,
                            Name = "ТЦ Балкания"
                        },
                        new
                        {
                            Id = 30,
                            Address = "Стачек пр-кт, 99",
                            CityId = 2,
                            Name = "ТЦ Континент"
                        },
                        new
                        {
                            Id = 31,
                            Address = "Савушкина улица, 141",
                            CityId = 2,
                            Name = "ТЦ Меркурий"
                        },
                        new
                        {
                            Id = 32,
                            Address = "Брантовская дорога, 3",
                            CityId = 2,
                            Name = "ТЦ Охта Молл"
                        },
                        new
                        {
                            Id = 33,
                            Address = "Энгельса пр-кт, 154",
                            CityId = 2,
                            Name = "ТЦ Гранд Каньон"
                        },
                        new
                        {
                            Id = 34,
                            Address = "Торфяная дорога, 7Т",
                            CityId = 2,
                            Name = "ТЦ Гулливер"
                        },
                        new
                        {
                            Id = 35,
                            Address = "Индустриальный пр-кт, 31",
                            CityId = 2,
                            Name = "ТЦ Индустриальный"
                        },
                        new
                        {
                            Id = 36,
                            Address = "Ленсовета улица, 97",
                            CityId = 2,
                            Name = "ТЦ Континент на Звездной"
                        },
                        new
                        {
                            Id = 37,
                            Address = "Белы Куна улица, 3",
                            CityId = 2,
                            Name = "ТЦ Международный"
                        },
                        new
                        {
                            Id = 38,
                            Address = "Фучика улица, 2",
                            CityId = 2,
                            Name = "ТЦ Рио"
                        },
                        new
                        {
                            Id = 39,
                            Address = "Большая Разночинная улица, 16",
                            CityId = 2,
                            Name = "ТЦ Чкаловский"
                        },
                        new
                        {
                            Id = 40,
                            Address = "Просвещения пр-кт, 80к1",
                            CityId = 2,
                            Name = "ТЦ Прометей"
                        },
                        new
                        {
                            Id = 41,
                            Address = "Типанова улица, 27/39",
                            CityId = 2,
                            Name = "ТЦ Космос"
                        },
                        new
                        {
                            Id = 42,
                            Address = "Приморский пр-кт, 72",
                            CityId = 2,
                            Name = "ТЦ Питерлэнд"
                        },
                        new
                        {
                            Id = 43,
                            Address = "Космонавтов пр-кт, 14",
                            CityId = 2,
                            Name = "ТЦ Питер Радуга"
                        },
                        new
                        {
                            Id = 44,
                            Address = "Тургеньевское ш., 27",
                            CityId = 4,
                            Name = "ТЦ Мега"
                        },
                        new
                        {
                            Id = 45,
                            Address = "ул. Ризы Фахретдина, 7",
                            CityId = 5,
                            Name = "ТЦ Девонский"
                        },
                        new
                        {
                            Id = 46,
                            Address = "192-й квартал, 12",
                            CityId = 6,
                            Name = "ТЦ Фестиваль"
                        },
                        new
                        {
                            Id = 47,
                            Address = "Ленина пр-кт, 200Б",
                            CityId = 7,
                            Name = "ТЦ Авеню"
                        },
                        new
                        {
                            Id = 48,
                            Address = "ул. Воровского, 69",
                            CityId = 8,
                            Name = "ТЦ Красная площадь"
                        },
                        new
                        {
                            Id = 49,
                            Address = "Ленинградский пр-кт, 38",
                            CityId = 9,
                            Name = "ТЦ Макси"
                        },
                        new
                        {
                            Id = 50,
                            Address = "ул. Советская, 25",
                            CityId = 9,
                            Name = "ТЦ Соломбала Молл"
                        },
                        new
                        {
                            Id = 51,
                            Address = "ул. Минусинская, 8",
                            CityId = 9,
                            Name = "ТЦ Три кота"
                        },
                        new
                        {
                            Id = 52,
                            Address = "ул. Магистральная, 29",
                            CityId = 9,
                            Name = "ТЦ Декстер"
                        },
                        new
                        {
                            Id = 53,
                            Address = "ул. Савушкина, 5",
                            CityId = 9,
                            Name = "ТЦ Сити"
                        },
                        new
                        {
                            Id = 54,
                            Address = "ул. Боевая, 25",
                            CityId = 9,
                            Name = "ТЦ Алимпик"
                        },
                        new
                        {
                            Id = 55,
                            Address = "ул. Трнавская, 24",
                            CityId = 10,
                            Name = "ТЦ Green House"
                        },
                        new
                        {
                            Id = 56,
                            Address = "ул. 30 лет Победы, 156",
                            CityId = 11,
                            Name = "ТЦ Айсберг"
                        },
                        new
                        {
                            Id = 57,
                            Address = "ул. Энтузиастов, 1",
                            CityId = 11,
                            Name = "ТЦ Балашовский Пассаж"
                        },
                        new
                        {
                            Id = 58,
                            Address = "Карла Маркса, 108",
                            CityId = 12,
                            Name = "СФ Карла Маркса"
                        },
                        new
                        {
                            Id = 59,
                            Address = "Ленина пр-кт, 102В",
                            CityId = 13,
                            Name = "ТЦ Пионер"
                        },
                        new
                        {
                            Id = 60,
                            Address = "ул. Павловский, 251А",
                            CityId = 13,
                            Name = "ТЦ Лето"
                        },
                        new
                        {
                            Id = 61,
                            Address = "пр-кт Строителей, 177",
                            CityId = 13,
                            Name = "ТЦ Galaxy"
                        },
                        new
                        {
                            Id = 62,
                            Address = "Богдана Хмельницкого пр-кт, 164",
                            CityId = 14,
                            Name = "ТЦ РИО"
                        },
                        new
                        {
                            Id = 63,
                            Address = "ул. Морозова, 9",
                            CityId = 15,
                            Name = "ТЦ Эссен"
                        },
                        new
                        {
                            Id = 64,
                            Address = "Радужный мкр., 7 к.1",
                            CityId = 16,
                            Name = "ТЦ Радужный"
                        },
                        new
                        {
                            Id = 65,
                            Address = "ул. Мухина, 114",
                            CityId = 17,
                            Name = "ТЦ Острова"
                        },
                        new
                        {
                            Id = 66,
                            Address = "ул. Объездная, 30",
                            CityId = 18,
                            Name = "ТЦ Аэропарк"
                        },
                        new
                        {
                            Id = 67,
                            Address = "ул. Ленина, 145",
                            CityId = 19,
                            Name = "ТЦ Эссен"
                        },
                        new
                        {
                            Id = 68,
                            Address = "ул. Ломоносова, 29",
                            CityId = 20,
                            Name = "ТЦ Мармелад"
                        },
                        new
                        {
                            Id = 69,
                            Address = "ул. Олимпийская, 6К1",
                            CityId = 21,
                            Name = "ТЦ Галерея 9-18"
                        },
                        new
                        {
                            Id = 70,
                            Address = "ул. Калинина, 8",
                            CityId = 22,
                            Name = "ТЦ Калина Молл"
                        },
                        new
                        {
                            Id = 71,
                            Address = "Некрасовская улица, 49А",
                            CityId = 22,
                            Name = "ТЦ Море"
                        },
                        new
                        {
                            Id = 72,
                            Address = "Московское шоссе, 3К",
                            CityId = 22,
                            Name = "ТЦ Алания Молл"
                        },
                        new
                        {
                            Id = 73,
                            Address = "ул. Астана Кесаева, 2а",
                            CityId = 22,
                            Name = "ТРЦ Столица"
                        },
                        new
                        {
                            Id = 74,
                            Address = "Тракторная улица, 45",
                            CityId = 23,
                            Name = "ТЦ Мегаторг"
                        },
                        new
                        {
                            Id = 75,
                            Address = "пр-кт Строителей, 9Б",
                            CityId = 23,
                            Name = "ТЦ Черемушки"
                        },
                        new
                        {
                            Id = 76,
                            Address = "Университетский пр-кт, 107",
                            CityId = 24,
                            Name = "ТЦ Акварель"
                        },
                        new
                        {
                            Id = 77,
                            Address = "б-р 30-летия Победы, 21",
                            CityId = 24,
                            Name = "ТЦ Парк Хаус"
                        },
                        new
                        {
                            Id = 78,
                            Address = "пр-кт им. В.И. Ленина, 54Б",
                            CityId = 24,
                            Name = "ТЦ Европа Сити Молл"
                        },
                        new
                        {
                            Id = 79,
                            Address = "ул. им. Землячки, 110Б",
                            CityId = 24,
                            Name = "ТЦ Мармелад"
                        },
                        new
                        {
                            Id = 80,
                            Address = "ул. Энтузиастов, 21В",
                            CityId = 25,
                            Name = "ТЦ Олимп"
                        },
                        new
                        {
                            Id = 81,
                            Address = "ул. Александрова, 18а",
                            CityId = 26,
                            Name = "ТЦ Волга Молл"
                        },
                        new
                        {
                            Id = 82,
                            Address = "п. Солнечный, Парковая улица, 3",
                            CityId = 26,
                            Name = "ТЦ Град"
                        },
                        new
                        {
                            Id = 83,
                            Address = "Ленинский пр-кт, 174П",
                            CityId = 26,
                            Name = "ТЦ Максимир"
                        },
                        new
                        {
                            Id = 84,
                            Address = "Московский пр-кт, 129/1",
                            CityId = 26,
                            Name = "ТЦ Московский проспект"
                        },
                        new
                        {
                            Id = 85,
                            Address = "ул. Генерала Кныша, 2а",
                            CityId = 27,
                            Name = "ТЦ Пилот"
                        },
                        new
                        {
                            Id = 86,
                            Address = "пр-кт Путина, 40",
                            CityId = 34,
                            Name = "ТЦ Грозный Молл"
                        },
                        new
                        {
                            Id = 87,
                            Address = "1-й мкр., 14а2/8",
                            CityId = 23,
                            Name = "ТЦ Галактика"
                        },
                        new
                        {
                            Id = 88,
                            Address = "ул. Гайдара, 61",
                            CityId = 45,
                            Name = "ТЦ ЦУМ"
                        },
                        new
                        {
                            Id = 89,
                            Address = "ул. Куйбышева, 170",
                            CityId = 43,
                            Name = "ТЦ Астра Сити"
                        },
                        new
                        {
                            Id = 90,
                            Address = "Краснодарская улица, 2",
                            CityId = 23,
                            Name = "ТЦ Перекресток"
                        },
                        new
                        {
                            Id = 91,
                            Address = "ул. 8 марта, 46",
                            CityId = 23,
                            Name = "ТЦ Гринвич"
                        },
                        new
                        {
                            Id = 92,
                            Address = "ул. Малышева, 5",
                            CityId = 23,
                            Name = "ТЦ Алатырь"
                        },
                        new
                        {
                            Id = 93,
                            Address = "пр-кт Космонавтов, 108д",
                            CityId = 22,
                            Name = "ТЦ Веер"
                        },
                        new
                        {
                            Id = 94,
                            Address = "ул. Вайнера, 9",
                            CityId = 33,
                            Name = "ТЦ Пассаж"
                        },
                        new
                        {
                            Id = 95,
                            Address = "ул. Щербакова, 4",
                            CityId = 44,
                            Name = "ТЦ Глобус"
                        },
                        new
                        {
                            Id = 96,
                            Address = "Московское ш., 18",
                            CityId = 11,
                            Name = "ТЦ Озон"
                        },
                        new
                        {
                            Id = 97,
                            Address = "ул. Лежневская, 55",
                            CityId = 32,
                            Name = "ТЦ Тополь"
                        },
                        new
                        {
                            Id = 98,
                            Address = "ул. 8 марта, 32",
                            CityId = 45,
                            Name = "ТЦ Серебряный Город"
                        },
                        new
                        {
                            Id = 99,
                            Address = "ул. Автозаводская, 3А",
                            CityId = 23,
                            Name = "ТЦ Столица"
                        },
                        new
                        {
                            Id = 100,
                            Address = "ул. Баранова, 87",
                            CityId = 1,
                            Name = "ТЦ Матрица"
                        },
                        new
                        {
                            Id = 101,
                            Address = "ул. 3 Июля, 25",
                            CityId = 2,
                            Name = "ТЦ Квартал"
                        },
                        new
                        {
                            Id = 102,
                            Address = "ул. Верхняя Набережная, 10",
                            CityId = 4,
                            Name = "ТЦ ЯркоМолл"
                        },
                        new
                        {
                            Id = 103,
                            Address = "ул. Сергеева, 3",
                            CityId = 9,
                            Name = "ТЦ Джем Молл"
                        },
                        new
                        {
                            Id = 104,
                            Address = "ул. Кирова, 6",
                            CityId = 5,
                            Name = "ТЦ Елка"
                        },
                        new
                        {
                            Id = 105,
                            Address = "ул. Красноармейская, 119",
                            CityId = 2,
                            Name = "ТЦ Зелень"
                        },
                        new
                        {
                            Id = 106,
                            Address = "пр-кт Победы, 91А",
                            CityId = 4,
                            Name = "ТЦ Южный"
                        },
                        new
                        {
                            Id = 107,
                            Address = "ул. Павлюхина, 91",
                            CityId = 33,
                            Name = "ТЦ Казань Молл"
                        },
                        new
                        {
                            Id = 108,
                            Address = "ул. Кул Гали, 9А",
                            CityId = 26,
                            Name = "ТЦ Эссен"
                        },
                        new
                        {
                            Id = 109,
                            Address = "ул. Юлиуса Фучика, 90",
                            CityId = 43,
                            Name = "ТЦ Франт"
                        },
                        new
                        {
                            Id = 110,
                            Address = "ул. академика Глушко, 16г",
                            CityId = 41,
                            Name = "ТЦ Академик"
                        },
                        new
                        {
                            Id = 111,
                            Address = "Ленинский пр-кт, 30",
                            CityId = 40,
                            Name = "ТЦ Плаза Калининград"
                        },
                        new
                        {
                            Id = 112,
                            Address = "п. Орловка, Приморское к-цо, 2",
                            CityId = 32,
                            Name = "ТЦ Балтия Молл"
                        },
                        new
                        {
                            Id = 113,
                            Address = "Московская улица, 338а",
                            CityId = 23,
                            Name = "ТЦ Торговый Квартал"
                        },
                        new
                        {
                            Id = 114,
                            Address = "Шахтёров пр-кт, 87",
                            CityId = 14,
                            Name = "ТЦ Север"
                        },
                        new
                        {
                            Id = 115,
                            Address = "Московский пр-кт, 19",
                            CityId = 41,
                            Name = "ТЦ Лето Сити"
                        },
                        new
                        {
                            Id = 116,
                            Address = "ул. Чайковского, 19Т",
                            CityId = 32,
                            Name = "ТЦ Эссен"
                        });
                });

            modelBuilder.Entity("Sinsay.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Sinsay.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<int>("ClothersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("ClothersId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("Sinsay.Models.AppUser", b =>
                {
                    b.HasOne("Sinsay.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Sinsay.Models.Order", b =>
                {
                    b.HasOne("Sinsay.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sinsay.Models.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sinsay.Models.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sinsay.Models.PickupPoint", "PickupPoint")
                        .WithMany()
                        .HasForeignKey("PickupPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("OrderStatus");

                    b.Navigation("PaymentMethod");

                    b.Navigation("PickupPoint");
                });

            modelBuilder.Entity("Sinsay.Models.PickupPoint", b =>
                {
                    b.HasOne("Sinsay.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Sinsay.Models.ShoppingCart", b =>
                {
                    b.HasOne("Sinsay.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sinsay.Models.Clothes", "Clothes")
                        .WithMany()
                        .HasForeignKey("ClothersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Clothes");
                });
#pragma warning restore 612, 618
        }
    }
}
